[project]
name = "playlistparser"
version = "3.0.0-beta.10"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Ville Säävuori", email = "ville@unessa.net" }]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.3.3", "pytest-cov>=6.0.0", "ruff>=0.7.4"]
