name: Test package

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.py'
      - 'tests/**'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'tests/**'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test
        run: pytest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Coverage
        run: pytest --cov=src/playlistparser --cov-report xml

      - name: Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
